version: '3.8'

services:
  app_blue_1:
    build: .
  app_blue_2:
    build: .

  app_green_1:
    build: .
  app_green_2:
    build: .

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf